metadata:
  name: adgear/streamio-ffmpeg
  description: Simple yet powerful ruby ffmpeg wrapper for reading metadata and transcoding movies
  labels:
    stack: Ruby
    jira-project: SDSP
    jira-board: 182
    public: false
    sensitive: false
  links:
  - url: https://adgear.atlassian.net/l/cp/9kD8ZGRe
    title: SDSP-API Confluence Page
spec:
  owner: cg-dsp-api
  type: tool
  lifecycle: production
